version: "3"

services:
  mongo:
    container_name: financial-manager-service-mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: financial_service
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - "27017:27017"
    volumes:
      - ./database-volume:/var/lib/mongodb/data
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge